import { Client } from '@/types/client.types';

export const mockClients: Client[] = [
  {
    id: 'client-1',
    firstName: 'María',
    lastName: 'Rodríguez',
    email: 'maria.rodriguez@email.com',
    phone: '+591 765-4321',
    address: 'Av. Arequipa 412, La Paz',
    rating: 4.8,
    totalOrders: 64,
    totalSpent: 3968,
    segment: 'vip',
    joinedAt: '2023-02-14',
  },
  {
    id: 'client-2',
    firstName: 'Carlos',
    lastName: 'González',
    email: 'carlos.g@email.com',
    phone: '+591 712-3456',
    address: 'Av. San Martín 225, La Paz',
    rating: 4.5,
    totalOrders: 51,
    totalSpent: 3162,
    segment: 'vip',
    joinedAt: '2023-05-08',
  },
  {
    id: 'client-3',
    firstName: 'Ana',
    lastName: 'Flores',
    email: 'ana.flores@email.com',
    phone: '+591 744-8899',
    address: 'Calle Ingavi 780, La Paz',
    rating: 4.9,
    totalOrders: 58,
    totalSpent: 4234,
    segment: 'vip',
    joinedAt: '2022-11-20',
  },
  {
    id: 'client-4',
    firstName: 'Jorge',
    lastName: 'Mamani',
    email: 'jorge.mamani@email.com',
    phone: '+591 799-1234',
    address: 'Zona Sur, Calacoto, La Paz',
    rating: 4.3,
    totalOrders: 38,
    totalSpent: 2356,
    segment: 'frequent',
    joinedAt: '2023-08-01',
  },
  {
    id: 'client-5',
    firstName: 'Lucía',
    lastName: 'Vargas',
    email: 'lucia.vargas@email.com',
    phone: '+591 733-5567',
    address: 'Av. Montenegro 310, La Paz',
    rating: 4.6,
    totalOrders: 29,
    totalSpent: 1798,
    segment: 'frequent',
    joinedAt: '2023-09-15',
  },
  {
    id: 'client-6',
    firstName: 'Roberto',
    lastName: 'Condori',
    email: 'r.condori@email.com',
    phone: '+591 788-2341',
    address: 'Calle Comercio 55, La Paz',
    rating: 4.1,
    totalOrders: 22,
    totalSpent: 1364,
    segment: 'frequent',
    joinedAt: '2024-01-10',
  },
  {
    id: 'client-7',
    firstName: 'Daniela',
    lastName: 'Quispe',
    email: 'dani.quispe@email.com',
    phone: '+591 711-9900',
    address: 'Sopocachi, La Paz',
    rating: 4.4,
    totalOrders: 24,
    totalSpent: 1488,
    segment: 'frequent',
    joinedAt: '2024-02-20',
  },
  {
    id: 'client-8',
    firstName: 'Sebastián',
    lastName: 'Cruz',
    email: 'seba.cruz@email.com',
    phone: '+591 766-4411',
    address: 'Miraflores, La Paz',
    rating: 4.0,
    totalOrders: 7,
    totalSpent: 434,
    segment: 'new',
    joinedAt: '2024-06-03',
  },
];
